/* ===== BILINGUAL NL / FR-BE ===== */
const LANG = {
  nl: {
    /* NAV */
    'nav.home':'Home',
    'nav.over':'Over ons',
    'nav.diensten':'Diensten',
    'nav.projecten':'Projecten',
    'nav.contact':'Contact',
    'nav.cta':'Offerte aanvragen',
    'nav.aria':'Hoofdnavigatie',
    'nav.menu-aria':'Menu openen',
    'mobile.menu-aria':'Mobiel menu',
    /* FOOTER */
    'footer.brand':'T.F.M. Construct BV is uw specialist in gevel- en dakwerken in Vlaanderen. Kwaliteit, vakmanschap en garantie staan bij ons centraal.',
    'footer.nav':'Navigatie',
    'footer.svc':'Diensten',
    'footer.copy':'&copy; 2026 T.F.M. Construct BV &mdash; Alle rechten voorbehouden',
    'footer.region':'Actief in heel <strong style="color:var(--gold)">Vlaanderen</strong>',
    'sticky.cta':'Offerte aanvragen',
    /* INDEX — HERO */
    'idx.hero.label':'T.F.M. Construct BV &mdash; Gevel- &amp; Dakspecialist in Vlaanderen',
    'idx.hero.h1':'Uw gevel en dak in vakkundige handen',
    'idx.hero.sub':'Van spuitkurk tot dakrenovatie &mdash; wij leveren totaaloplossingen voor gevel en dak, voor particulieren en bedrijven in heel Vlaanderen.',
    'idx.hero.btn1':'Gratis offerte aanvragen',
    'idx.hero.btn2':'Onze projecten bekijken',
    'stat.garantie':'Garantie',
    'stat.offerte':'Offerte',
    'stat.plaatsbezoek':'Plaatsbezoek',
    /* INDEX — DIENSTEN PREVIEW */
    'idx.svc.label':'Onze specialisaties',
    'idx.svc.title':'Wat wij voor u doen',
    'idx.svc.sub':'Met jarenlange expertise in gevel- en dakrenovatie bieden wij u de meest geschikte oplossing voor elk gebouw in Vlaanderen.',
    'idx.gevel.title':'Gevelwerken',
    'idx.gevel.count':'5 diensten',
    'idx.dak.title':'Dakwerken',
    'idx.dak.count':'2 diensten',
    'idx.svc.more':'Meer info &rarr;',
    /* service cards */
    'svc.gevelisolatie':'Gevelisolatie',
    'svc.gevelisolatie.desc':'Thermische buitengevelisolatie die uw energierekening verlaagt en het wooncomfort verhoogt.',
    'svc.spuitkurk':'Spuitkurk',
    'svc.spuitkurk.desc':'Dampopen, isolerend en decoratief. Spuitkurk is een duurzame gevelafwerking met uitstekende eigenschappen.',
    'svc.crepi':'Crepi',
    'svc.crepi.desc':'Traditionele gevelbepleistering die uw gevel beschermt en een strakke, esthetische afwerking geeft.',
    'svc.steenstrips':'Steenstrips',
    'svc.steenstrips.desc':'De uitstraling van natuursteen of baksteen zonder de hoge kostprijs. Lichtgewicht, vochtbestendig en verfijnd.',
    'svc.kaleien':'Kaleien',
    'svc.kaleien.desc':'Kalkhoudende afwerking voor historische en erfgoedpanden. Ademend, duurzaam en authentiek.',
    'svc.dakrenovatie':'Dakrenovatie',
    'svc.dakrenovatie.desc':'Volledige dakrenovatie door erkende vakmensen. Wij herstellen en vernieuwen uw dak met hoogwaardige materialen en garantie.',
    'svc.dakisolatie':'Dakisolatie',
    'svc.dakisolatie.desc':'Effectieve dakisolatie die energieverlies drastisch vermindert. Betere thermische prestaties en lager energieverbruik.',
    'idx.svc.all':'Alle diensten bekijken',
    /* INDEX — MAP */
    'idx.map.label':'Werkgebied',
    'idx.map.title':'Actief in heel Vlaanderen',
    'idx.map.p1':'Van kust tot Kempen &mdash; wij komen naar u toe. T.F.M. Construct BV is actief in alle vijf de Vlaamse provincies en voert opdrachten uit bij particulieren, bedrijven en overheden.',
    'idx.map.p2':'Of u nu in Gent, Antwerpen, Brugge, Hasselt of Leuven woont &mdash; onze vakbekwame teams staan voor u klaar voor een gratis plaatsbezoek en vrijblijvende offerte.',
    'idx.map.btn':'Gratis plaatsbezoek aanvragen',
    /* INDEX — PROCESS */
    'process.label':'Werkwijze',
    'process.title':'Hoe wij werken',
    'step1.title':'Contact &amp; Aanvraag',
    'step1.p':'U neemt contact op via onze website, telefoon of WhatsApp. We beantwoorden elke aanvraag snel en professioneel.',
    'step2.title':'Gratis Plaatsbezoek',
    'step2.p':'Onze expert komt ter plaatse om de situatie te beoordelen en de beste oplossing voor uw gevel of dak voor te stellen.',
    'step3.title':'Offerte binnen 48u',
    'step3.p':'U ontvangt een gedetailleerde en transparante offerte zonder verrassingen, binnen 48 uur na het plaatsbezoek.',
    'step4.title':'Vakkundige Uitvoering',
    'step4.p':'Na akkoord voert ons team het werk uit met hoogwaardige materialen en 10 jaar garantie op het resultaat.',
    /* INDEX — VOOR & NA */
    'vn.label':'Realisaties',
    'vn.title':'Voor &amp; Na',
    'vn.sub':'Ontdek de transformatie die T.F.M. Construct BV realiseert. Elk project getuigt van vakmanschap en aandacht voor detail.',
    'vn.voor.steel':'Voor &mdash; Steenstrips',
    'vn.na.steel':'Na &mdash; Steenstrips',
    'vn.voor.crepi':'Voor &mdash; Crepi',
    'vn.na.crepi':'Na &mdash; Crepi',
    'vn.btn':'Alle projecten bekijken',
    /* INDEX — CTA */
    'cta.h2':'Klaar voor een perfecte gevel of dak?',
    'cta.p':'Neem vandaag nog contact op voor een gratis plaatsbezoek en vrijblijvende offerte. Wij staan voor u klaar in heel Vlaanderen.',
    'cta.btn':'Offerte aanvragen',
    /* INDEX — CONTACT FORM */
    'form.label':'Neem contact op',
    'form.title':'Vraag uw offerte aan',
    'form.naam':'Naam *',
    'form.tel':'Telefoonnummer *',
    'form.email':'E-mailadres *',
    'form.bericht':'Bericht',
    'form.submit':'Verstuur aanvraag',
    'form.note':'Wij antwoorden binnen 24 uur. Uw gegevens worden nooit gedeeld met derden.',
    'form.ph.naam':'Jan Janssen',
    'form.ph.bericht':'Beschrijf uw project...',
    'form.tel.label':'Telefoon',
    'form.email.label':'E-mail',
    'form.wa.label':'WhatsApp',
    'form.wa.link':'Stuur een bericht',
    'form.uur.label':'Openingsuren',
    'form.uur.val':'Ma&ndash;Vr: 07:00&ndash;18:00<br>Za: 08:00&ndash;14:00',
    /* DIENSTEN PAGE */
    'dnt.hero.label':'Wat wij aanbieden',
    'dnt.hero.h1':'Onze gevelwerken',
    'dnt.cat1.label':'Categorie 01',
    'dnt.cat1.title':'Gevelwerken',
    'dnt.cat1.sub':'Alle geveloplossingen onder één dak',
    'dnt.cat1.p':'T.F.M. Construct BV is gespecialiseerd in vijf gevelafwerkingstechnieken, elk met eigen eigenschappen en toepassingsgebieden. Wij adviseren u kosteloos welke oplossing het best past bij uw gebouw en budget.',
    'dnt.d01.label':'Dienst 01',
    'dnt.d01.h2':'Gevelisolatie',
    'dnt.d01.p1':'Buitengevelisolatie (ETICS) is de meest efficiënte manier om uw woning thermisch te isoleren zonder binnenoppervlak te verliezen. Isolatieplaten worden aan de buitenzijde bevestigd en afgewerkt met een decoratieve laag.',
    'dnt.d01.p2':'U bespaart tot 30% op uw energiefactuur en verhoogt het wooncomfort. Bovendien voldoet u aan de steeds strengere EPB-vereisten in Vlaanderen en geniet u van Vlaamse premies.',
    'dnt.d01.f1':'Tot 30% besparing op energiefactuur',
    'dnt.d01.f2':'Warm in de winter, koel in de zomer',
    'dnt.d01.f3':'Geen verlies van binnenoppervlak',
    'dnt.d01.f4':'Voldoet aan EPB-vereisten Vlaanderen',
    'dnt.d01.f5':'Eliminatie van koudebruggen',
    'dnt.d01.f6':'Combineerbaar met spuitkurk of crepi',
    'dnt.d01.f7':'10 jaar garantie van T.F.M. Construct BV',
    'dnt.d01.btn':'Offerte voor gevelisolatie',
    'dnt.d02.label':'Dienst 02',
    'dnt.d02.h2':'Spuitkurk',
    'dnt.d02.p1':'Spuitkurk is de populairste gevelafwerking in Vlaanderen. Op basis van natuurlijke kurkkorrels en acrylhars wordt het product gespoten op de gevel, wat een unieke, duurzame en decoratieve textuur geeft.',
    'dnt.d02.p2':'Dankzij de dampopen structuur kan de gevel blijven ademen — vochtproblemen en schimmelvorming worden zo voorkomen. Uitstekend voor zowel renovatie als nieuwbouw.',
    'dnt.d02.f1':'Dampopen &mdash; gevel blijft ademen',
    'dnt.d02.f2':'Thermisch en akoestisch isolerend',
    'dnt.d02.f3':'Breed kleurenpallet &mdash; volledig op maat',
    'dnt.d02.f4':'Onderhoudsvriendelijk en zelfreinigend',
    'dnt.d02.f5':'UV- en vorstbestendig',
    'dnt.d02.f6':'Geschikt voor nieuwbouw en renovatie',
    'dnt.d02.f7':'10 jaar garantie van T.F.M. Construct BV',
    'dnt.d02.btn':'Offerte voor spuitkurk',
    'dnt.d03.label':'Dienst 03',
    'dnt.d03.h2':'Crepi',
    'dnt.d03.p1':'Crepi (gevelbepleistering) is een van de meest toegepaste gevelafwerkingen in de Belgische bouwsector. Het beschermt de gevel optimaal tegen regen, wind en temperatuurschommelingen.',
    'dnt.d03.p2':'Bij T.F.M. Construct BV werken wij met kwalitatieve crepi-producten aangebracht door ervaren vaklui. Resultaat: een strakke, esthetische en duurzame afwerking die jarenlang mooi blijft.',
    'dnt.d03.f1':'Optimale bescherming tegen weersomstandigheden',
    'dnt.d03.f2':'Strakke en esthetische afwerking',
    'dnt.d03.f3':'Diverse texturen en kleuren beschikbaar',
    'dnt.d03.f4':'Dampopen en vochtwerend',
    'dnt.d03.f5':'Geschikt voor nieuwbouw en renovatie',
    'dnt.d03.f6':'Onderhoudsvriendelijk en duurzaam',
    'dnt.d03.f7':'10 jaar garantie van T.F.M. Construct BV',
    'dnt.d03.btn':'Offerte voor crepi',
    'dnt.d04.label':'Dienst 04',
    'dnt.d04.h2':'Steenstrips',
    'dnt.d04.p1':'Steenstrips geven uw gevel de uitstraling van natuursteen of baksteen zonder de hoge kostprijs. Lichtgewicht, vochtbestendig en esthetisch verfijnd &mdash; ideaal voor renovaties en nieuwbouw.',
    'dnt.d04.p2':'Ze zijn eenvoudig te plaatsen op bestaande gevels en bieden een grote verscheidenheid aan kleuren, texturen en formaten. Zowel voor interieur als exterieur.',
    'dnt.d04.f1':'Authentieke steen- of baksteenlook',
    'dnt.d04.f2':'Lichtgewicht &amp; eenvoudig te plaatsen',
    'dnt.d04.f3':'Vochtbestendig &amp; onderhoudsvriendelijk',
    'dnt.d04.f4':'Groot aanbod kleuren en texturen',
    'dnt.d04.f5':'Geschikt voor binnen en buiten',
    'dnt.d04.f6':'Combineerbaar met andere gevelafwerkingen',
    'dnt.d04.f7':'10 jaar garantie van T.F.M. Construct BV',
    'dnt.d04.btn':'Offerte voor steenstrips',
    'dnt.d05.label':'Dienst 05',
    'dnt.d05.h2':'Kaleien',
    'dnt.d05.p1':'Kaleien is een eeuwenoude techniek op basis van kalk, opnieuw sterk in opmars voor historische panden en moderne gebouwen met een authentieke uitstraling. T.F.M. Construct BV heeft ervaren specialisten voor dit delicate vakwerk.',
    'dnt.d05.p2':'De ademende eigenschappen van kalk maken kaleien uitermate geschikt voor erfgoedgebouwen. Het reguleert het vochtgehalte in de gevel en voorkomt zoutuitslagen en condensatie.',
    'dnt.d05.f1':'100% natuurlijk en ademend (kalk)',
    'dnt.d05.f2':'Ideaal voor historische en erfgoedpanden',
    'dnt.d05.f3':'Reguleert vochtgehalte in de gevel',
    'dnt.d05.f4':'Bacterio- en schimmelwerend van nature',
    'dnt.d05.f5':'Authentieke, warme uitstraling',
    'dnt.d05.f6':'Milieuvriendelijk &mdash; lage ecologische voetafdruk',
    'dnt.d05.f7':'Compatibel met restauratienormen voor monumenten',
    'dnt.d05.btn':'Offerte voor kaleien',
    'dnt.cat2.label':'Categorie 02',
    'dnt.cat2.title':'Dakwerken',
    'dnt.cat2.sub':'Uw dak in vakkundige handen',
    'dnt.d06.label':'Dienst 06',
    'dnt.d06.h2':'Dakrenovatie',
    'dnt.d06.p1':'Een verouderd dak vroegtijdig aanpakken bespaart u grote kosten op lange termijn. T.F.M. Construct BV voert dakrenovaties uit van A tot Z: van inspectie en diagnose tot volledige vervanging of gedeeltelijke herstelling.',
    'dnt.d06.f1':'Grondige dakinspectie',
    'dnt.d06.f2':'Vervanging van dakpannen en leien',
    'dnt.d06.f3':'Herstelling van dakgoten en afvoeren',
    'dnt.d06.f4':'Behandeling van schimmel en mossen',
    'dnt.d06.f5':'Nieuwe dakbedekking naar keuze',
    'dnt.d06.f6':'10 jaar garantie op uitgevoerde werken',
    'dnt.d06.btn':'Offerte voor dakrenovatie',
    'dnt.d07.label':'Dienst 07',
    'dnt.d07.h2':'Dakisolatie',
    'dnt.d07.p1':'Tot 30% van de warmte in uw woning gaat verloren via het dak. Dakisolatie is dan ook de meest rendabele investering die u kunt doen. T.F.M. Construct BV plaatst kwalitatieve dakisolatie die voldoet aan alle Vlaamse normen.',
    'dnt.d07.f1':'Binnenisolatie (kepers of zoldervloer)',
    'dnt.d07.f2':'Buitenisolatie (sarking)',
    'dnt.d07.f3':'Hoge isolatiewaarden (U &le; 0.24 W/m&sup2;K)',
    'dnt.d07.f4':'Erkend door Vlaanderen (premies mogelijk)',
    'dnt.d07.f5':'Condensatieproblemen verholpen',
    'dnt.d07.f6':'10 jaar garantie',
    'dnt.d07.btn':'Offerte voor dakisolatie',
    'dnt.cta.h2':'Welke geveloplossing past bij u?',
    'dnt.cta.p':'Onze expert adviseert u kosteloos tijdens een gratis plaatsbezoek. Geen verplichtingen, wel een eerlijk en deskundig advies.',
    'dnt.cta.btn':'Gratis advies aanvragen',
    /* PROJECTEN */
    'prj.hero.label':'Onze realisaties',
    'prj.hero.h1':'Projecten',
    'prj.hero.sub':'Het resultaat spreekt voor zich',
    'prj.voor':'Voor',
    'prj.na':'Na',
    'prj.toggle':'Bekijk uitvoering',
    'prj.situatie':'Situatie',
    'prj.vraag':'Vraag van de klant',
    'prj.aanpak':'Onze aanpak',
    'prj.resultaat':'Resultaat',
    /* project 01 crepi */
    'prj.01.type':'Crepi',
    'prj.01.title':'Nieuwbouw &mdash; gevelisolatie met crepi afwerking',
    'prj.01.sit':'Nieuwbouw woning zonder afwerking',
    'prj.01.vraag':'Volledige gevelafwerking met isolatie en crepi',
    'prj.01.aanpak':'EPS-isolatieplaten aangebracht, basispleister met wapeningsnet, primer en crepi als afwerklaag',
    'prj.01.res':'Moderne, energiezuinige gevel met strakke crepi afwerking en 10 jaar garantie',
    /* project 02 steenstrips */
    'prj.02.type':'Steenstrips',
    'prj.02.title':'Gevelrenovatie &mdash; thermische isolatie met steenstrips',
    'prj.02.sit':'Verouderde gevel zonder isolatie',
    'prj.02.vraag':'Betere isolatie met authentieke uitstraling',
    'prj.02.aanpak':'Buitengevelisolatie aangebracht, afgewerkt met steenstrips voor authentieke baksteenlook',
    'prj.02.res':'Energiezuinige woning met tijdloze baksteenuitstraling en verhoogd wooncomfort',
    /* project 03 kaleien */
    'prj.03.type':'Kaleien',
    'prj.03.title':'Renovatie &mdash; kaleien voor vernieuwd uitzicht en bescherming',
    'prj.03.sit':'Verouderde gevel met verweerde afwerking',
    'prj.03.vraag':'Vernieuwd uitzicht en optimale vochtbescherming',
    'prj.03.aanpak':'Gevel gereinigd, gekalkt met traditionele kaleimethode in meerdere lagen',
    'prj.03.res':'Fris, authentiek uitzicht met uitstekende vochtregulering en ademende gevel',
    /* project 04 spuitkurk */
    'prj.04.type':'Spuitkurk',
    'prj.04.title':'Residenti&euml;le woning &mdash; gevelrenovatie met spuitkurk',
    'prj.04.sit':'Verouderde gevel met gescheurde en verkleurde bepleistering',
    'prj.04.vraag':'Frisse, duurzame gevelafwerking zonder grote verbouwing',
    'prj.04.aanpak':'Reiniging van de gevel, herstel van scheuren, spuitkurk in twee lagen aangebracht',
    'prj.04.res':'Egale, dampopen afwerking &mdash; waterdicht en onderhoudsarm',
    /* CONTACT */
    'cnt.hero.label':'Neem contact op',
    'cnt.hero.h1':'Contact &amp; Offerte',
    'cnt.form.label':'Gratis en vrijblijvend',
    'cnt.form.title':'Vraag uw offerte aan',
    'cnt.form.sub':'Vul het formulier in en wij nemen binnen 24 uur contact met u op. Of bel ons direct voor een snelle afspraak.',
    'cnt.naam':'Naam *',
    'cnt.bedrijf':'Bedrijfsnaam <span style="font-weight:400;text-transform:none;font-family:Inter,sans-serif;font-size:.8rem;color:#888">(optioneel)</span>',
    'cnt.tel':'Telefoonnummer *',
    'cnt.email':'E-mailadres *',
    'cnt.dienst':'Gewenste dienst',
    'cnt.dienst.select':'Selecteer een dienst',
    'cnt.dienst.combo':'Combinatie van diensten',
    'cnt.dienst.advies':'Advies / Ik weet het nog niet',
    'cnt.bericht':'Bericht *',
    'cnt.ph.naam':'Jan Janssen',
    'cnt.ph.bedrijf':'Uw bedrijf BV',
    'cnt.ph.bericht':'Beschrijf uw project, adres, gewenste timing...',
    'cnt.submit':'Verstuur aanvraag',
    'cnt.note':'Wij antwoorden binnen 24 uur. Uw gegevens worden strikt vertrouwelijk behandeld en nooit gedeeld met derden.',
    'cnt.tel.label':'Telefoon',
    'cnt.tel.sub':'Ma&ndash;Vr 07:00&ndash;18:00',
    'cnt.email.label':'E-mail',
    'cnt.email.sub':'Antwoord binnen 24 uur',
    'cnt.wa.label':'WhatsApp',
    'cnt.wa.sub':'Stuur een bericht &mdash; snel antwoord',
    'cnt.uur.label':'Openingsuren',
    'cnt.uur.val':'Maandag &ndash; Vrijdag: 07:00 &ndash; 18:00<br>Zaterdag: 08:00 &ndash; 14:00<br>Zondag: Gesloten',
    'cnt.werk.label':'Werkgebied',
    'cnt.werk.val':'Actief in heel Vlaanderen<br>West-Vl., Oost-Vl., Antwerpen,<br>Vl.-Brabant &amp; Limburg',
    'cnt.adres.label':'Adres',
    'cnt.wa.section.label':'Snelste weg',
    'cnt.wa.h2':'Liever chatten via WhatsApp?',
    'cnt.wa.p':'Stuur ons een berichtje en we reageren zo snel mogelijk. Foto\'s meesturen van uw gevel? Dat kan ook via WhatsApp!',
    'cnt.wa.btn':'Chat via WhatsApp',
    /* OVER ONS */
    'ons.hero.label':'T.F.M. Construct BV',
    'ons.hero.h1':'Over T.F.M. Construct BV',
    'ons.story.label':'Ons verhaal',
    'ons.story.title':'Gegrond op passie voor vakmanschap',
    'ons.story.p1':'T.F.M. Construct BV ontstond uit een diepe passie voor bouwwerken en een onwrikbare overtuiging dat elk gebouw een kwalitatieve, duurzame afwerking verdient &mdash; zowel de gevel als het dak. Van bij het begin kozen wij resoluut voor vakmanschap, hoogwaardige materialen en een persoonlijke aanpak.',
    'ons.story.p2':'Actief in heel Vlaanderen, van de kust tot de Kempen, bouwen wij dagelijks aan de reputatie die ons onderscheidt: eerlijk advies, transparante prijzen, en een resultaat waar zowel wij als onze klanten trots op zijn.',
    'ons.story.p3':'Onze teams bestaan uit ervaren vaklui die elk project met dezelfde zorg en toewijding aanpakken, ongeacht de omvang. Of het nu gaat om een crepi-afwerking, een gevelrenovatie met spuitkurk, een dakrenovatie of dakisolatie &mdash; T.F.M. Construct BV levert altijd het beste resultaat.',
    'ons.story.p4':'Wij geloven in langetermijnrelaties met onze klanten. Daarom bieden wij 10 jaar garantie op al onze gevel- en dakwerken en staan wij ook na de oplevering voor u klaar.',
    'ons.val.label':'Onze kernwaarden',
    'ons.val.title':'Waar wij voor staan',
    'ons.kwaliteit.h':'Kwaliteit',
    'ons.kwaliteit.p':'Wij werken uitsluitend met gecertificeerde materialen van toonaangevende merken. Elk project wordt afgewerkt met oog voor detail en conform de strengste normen.',
    'ons.betrouw.h':'Betrouwbaarheid',
    'ons.betrouw.p':'Wij komen onze afspraken na. Transparante communicatie, duidelijke offertes zonder verborgen kosten en tijdige uitvoering zijn onze basisprincipes.',
    'ons.vakman.h':'Vakmanschap',
    'ons.vakman.p':'Onze vaklui beschikken over jarenlange ervaring en volgen voortdurend bij- en nascholingen. Gevel- en dakwerken zijn vakken die wij met trots uitoefenen.',
    'ons.why.label':'Waarom kiezen voor ons',
    'ons.why.title':'Uw voordelen met T.F.M. Construct BV',
    'ons.why.sub':'Wij onderscheiden ons door onze persoonlijke aanpak, technische expertise en onwrikbare kwaliteitsgarantie. Hier zijn de voornaamste redenen waarom onze klanten voor ons kiezen:',
    'ons.adv1':'10 jaar garantie op alle gevel- en dakwerken',
    'ons.adv2':'Gratis plaatsbezoek en vrijblijvende offerte',
    'ons.adv3':'Offerte binnen 48 uur na bezoek',
    'ons.adv4':'Actief in heel Vlaanderen',
    'ons.adv5':'Erkend aannemer &mdash; gecertificeerd vakman',
    'ons.adv6':'Uitsluitend hoogwaardige, gecertificeerde materialen',
    'ons.adv7':'Transparante en eerlijke prijsvorming',
    'ons.adv8':'Persoonlijk contactpunt tijdens het project',
    'ons.adv9':'Schone en veilige werkplek gegarandeerd',
    'ons.adv10':'Snelle interventie bij vragen of problemen',
    'ons.adv11':'Ervaren teams met specialisatie per dienst',
    'ons.adv12':'Nazorg en opvolging na oplevering',
    'ons.cta.h2':'Klaar om uw gevel of dak te laten vernieuwen?',
    'ons.cta.p':'Neem vandaag nog contact op. Wij plannen een gratis plaatsbezoek en bezorgen u een transparante offerte zonder verplichtingen.',
    'ons.cta.btn':'Contact opnemen',
    /* BREADCRUMB */
    'bc.home':'Home',
    'bc.diensten':'Diensten',
    'bc.projecten':'Projecten',
    'bc.contact':'Contact',
    'bc.over':'Over ons',
  },

  fr: {
    /* NAV */
    'nav.home':'Accueil',
    'nav.over':'À propos',
    'nav.diensten':'Services',
    'nav.projecten':'Réalisations',
    'nav.contact':'Contact',
    'nav.cta':'Demander un devis',
    'nav.aria':'Navigation principale',
    'nav.menu-aria':'Ouvrir le menu',
    'mobile.menu-aria':'Menu mobile',
    /* FOOTER */
    'footer.brand':'T.F.M. Construct BV est votre spécialiste en travaux de façade et toiture en Flandre. Qualité, savoir-faire et garantie sont au cœur de notre métier.',
    'footer.nav':'Navigation',
    'footer.svc':'Services',
    'footer.copy':'&copy; 2026 T.F.M. Construct BV &mdash; Tous droits réservés',
    'footer.region':'Actif dans toute la <strong style="color:var(--gold)">Flandre</strong>',
    'sticky.cta':'Demander un devis',
    /* INDEX — HERO */
    'idx.hero.label':'T.F.M. Construct BV &mdash; Spécialiste façades &amp; toitures en Flandre',
    'idx.hero.h1':'Votre façade et toiture entre des mains expertes',
    'idx.hero.sub':'De l\'enduit liège à la rénovation de toiture &mdash; nous offrons des solutions complètes pour façades et toitures, pour particuliers et entreprises dans toute la Flandre.',
    'idx.hero.btn1':'Demander un devis gratuit',
    'idx.hero.btn2':'Voir nos réalisations',
    'stat.garantie':'Garantie',
    'stat.offerte':'Devis',
    'stat.plaatsbezoek':'Visite gratuite',
    /* INDEX — DIENSTEN PREVIEW */
    'idx.svc.label':'Nos spécialités',
    'idx.svc.title':'Ce que nous faisons pour vous',
    'idx.svc.sub':'Forts de nombreuses années d\'expertise en rénovation de façades et toitures, nous vous proposons la solution la plus adaptée à chaque bâtiment en Flandre.',
    'idx.gevel.title':'Travaux de façade',
    'idx.gevel.count':'5 services',
    'idx.dak.title':'Travaux de toiture',
    'idx.dak.count':'2 services',
    'idx.svc.more':'En savoir plus &rarr;',
    /* service cards */
    'svc.gevelisolatie':'Isolation de façade',
    'svc.gevelisolatie.desc':'Isolation thermique par l\'extérieur qui réduit votre facture énergétique et améliore le confort de vie.',
    'svc.spuitkurk':'Enduit liège projeté',
    'svc.spuitkurk.desc':'Respirant, isolant et décoratif. L\'enduit liège est un revêtement de façade durable aux propriétés remarquables.',
    'svc.crepi':'Crépi',
    'svc.crepi.desc':'Enduit de façade traditionnel qui protège votre mur et offre une finition soignée et esthétique.',
    'svc.steenstrips':'Plaquettes de parement',
    'svc.steenstrips.desc':'L\'aspect de la pierre naturelle ou de la brique sans le coût élevé. Léger, résistant à l\'humidité et raffiné.',
    'svc.kaleien':'Badigeon à la chaux',
    'svc.kaleien.desc':'Finition à base de chaux pour les bâtiments historiques et patrimoniaux. Respirant, durable et authentique.',
    'svc.dakrenovatie':'Rénovation de toiture',
    'svc.dakrenovatie.desc':'Rénovation complète de toiture par des artisans qualifiés. Nous réparons et renouvelons votre toit avec des matériaux de qualité et une garantie.',
    'svc.dakisolatie':'Isolation de toiture',
    'svc.dakisolatie.desc':'Isolation de toiture efficace qui réduit considérablement les déperditions énergétiques. Meilleures performances thermiques et consommation réduite.',
    'idx.svc.all':'Voir tous les services',
    /* INDEX — MAP */
    'idx.map.label':'Zone d\'intervention',
    'idx.map.title':'Actif dans toute la Flandre',
    'idx.map.p1':'De la côte aux Campines &mdash; nous nous déplaçons chez vous. T.F.M. Construct BV est actif dans les cinq provinces flamandes et réalise des chantiers pour particuliers, entreprises et pouvoirs publics.',
    'idx.map.p2':'Que vous habitiez à Gand, Anvers, Bruges, Hasselt ou Louvain &mdash; nos équipes qualifiées sont disponibles pour une visite gratuite et un devis sans engagement.',
    'idx.map.btn':'Demander une visite gratuite',
    /* INDEX — PROCESS */
    'process.label':'Notre méthode',
    'process.title':'Comment nous travaillons',
    'step1.title':'Contact &amp; Demande',
    'step1.p':'Vous nous contactez via notre site web, par téléphone ou WhatsApp. Nous répondons à chaque demande rapidement et professionnellement.',
    'step2.title':'Visite gratuite sur place',
    'step2.p':'Notre expert se déplace pour évaluer la situation et vous proposer la meilleure solution pour votre façade ou toiture.',
    'step3.title':'Devis sous 48h',
    'step3.p':'Vous recevez un devis détaillé et transparent sans surprises, dans les 48 heures suivant la visite.',
    'step4.title':'Exécution professionnelle',
    'step4.p':'Après accord, notre équipe réalise les travaux avec des matériaux de qualité et une garantie de 10 ans sur le résultat.',
    /* INDEX — VOOR & NA */
    'vn.label':'Réalisations',
    'vn.title':'Avant &amp; Après',
    'vn.sub':'Découvrez la transformation que T.F.M. Construct BV réalise. Chaque projet témoigne du savoir-faire et du soin apporté aux détails.',
    'vn.voor.steel':'Avant &mdash; Plaquettes',
    'vn.na.steel':'Après &mdash; Plaquettes',
    'vn.voor.crepi':'Avant &mdash; Crépi',
    'vn.na.crepi':'Après &mdash; Crépi',
    'vn.btn':'Voir toutes les réalisations',
    /* INDEX — CTA */
    'cta.h2':'Prêt pour une façade ou une toiture parfaite&nbsp;?',
    'cta.p':'Contactez-nous dès aujourd\'hui pour une visite gratuite et un devis sans engagement. Nous sommes à votre service dans toute la Flandre.',
    'cta.btn':'Demander un devis',
    /* INDEX — CONTACT FORM */
    'form.label':'Nous contacter',
    'form.title':'Demandez votre devis',
    'form.naam':'Nom *',
    'form.tel':'Numéro de téléphone *',
    'form.email':'Adresse e-mail *',
    'form.bericht':'Message',
    'form.submit':'Envoyer la demande',
    'form.note':'Nous répondons dans les 24 heures. Vos données ne seront jamais partagées avec des tiers.',
    'form.ph.naam':'Jean Dupont',
    'form.ph.bericht':'Décrivez votre projet...',
    'form.tel.label':'Téléphone',
    'form.email.label':'E-mail',
    'form.wa.label':'WhatsApp',
    'form.wa.link':'Envoyer un message',
    'form.uur.label':'Heures d\'ouverture',
    'form.uur.val':'Lu&ndash;Ve: 07:00&ndash;18:00<br>Sa: 08:00&ndash;14:00',
    /* DIENSTEN PAGE */
    'dnt.hero.label':'Ce que nous proposons',
    'dnt.hero.h1':'Nos travaux de façade',
    'dnt.cat1.label':'Catégorie 01',
    'dnt.cat1.title':'Travaux de façade',
    'dnt.cat1.sub':'Toutes les solutions façade sous un même toit',
    'dnt.cat1.p':'T.F.M. Construct BV est spécialisé dans cinq techniques de revêtement de façade, chacune avec ses caractéristiques et domaines d\'application. Nous vous conseillons gratuitement sur la solution la mieux adaptée à votre bâtiment et votre budget.',
    'dnt.d01.label':'Service 01',
    'dnt.d01.h2':'Isolation de façade',
    'dnt.d01.p1':'L\'isolation thermique par l\'extérieur (ITE / ETICS) est la méthode la plus efficace pour isoler thermiquement votre habitation sans perdre de surface intérieure. Les panneaux isolants sont fixés en façade et finis avec une couche décorative.',
    'dnt.d01.p2':'Vous économisez jusqu\'à 30% sur votre facture énergétique et améliorez le confort de vie. Vous répondez également aux exigences PEB croissantes et bénéficiez des primes disponibles.',
    'dnt.d01.f1':'Jusqu\'à 30% d\'économie sur la facture énergétique',
    'dnt.d01.f2':'Chaud en hiver, frais en été',
    'dnt.d01.f3':'Aucune perte de surface intérieure',
    'dnt.d01.f4':'Conforme aux exigences PEB',
    'dnt.d01.f5':'Élimination des ponts thermiques',
    'dnt.d01.f6':'Compatible avec enduit liège ou crépi',
    'dnt.d01.f7':'Garantie 10 ans T.F.M. Construct BV',
    'dnt.d01.btn':'Devis pour isolation de façade',
    'dnt.d02.label':'Service 02',
    'dnt.d02.h2':'Enduit liège projeté',
    'dnt.d02.p1':'L\'enduit liège projeté est l\'un des revêtements de façade les plus populaires en Belgique. À base de granulés de liège naturels et de résine acrylique, le produit est projeté sur la façade, donnant une texture unique, durable et décorative.',
    'dnt.d02.p2':'Grâce à sa structure respirante, la façade peut continuer à transpirer — les problèmes d\'humidité et de moisissures sont ainsi évités. Excellent pour la rénovation comme pour les constructions neuves.',
    'dnt.d02.f1':'Respirant &mdash; la façade reste saine',
    'dnt.d02.f2':'Isolant thermique et acoustique',
    'dnt.d02.f3':'Large palette de couleurs &mdash; entièrement sur mesure',
    'dnt.d02.f4':'Facile d\'entretien et autonettoyant',
    'dnt.d02.f5':'Résistant aux UV et au gel',
    'dnt.d02.f6':'Convient pour neuf et rénovation',
    'dnt.d02.f7':'Garantie 10 ans T.F.M. Construct BV',
    'dnt.d02.btn':'Devis pour enduit liège',
    'dnt.d03.label':'Service 03',
    'dnt.d03.h2':'Crépi',
    'dnt.d03.p1':'Le crépi (enduit de façade) est l\'un des revêtements de façade les plus utilisés dans le secteur belge de la construction. Il protège de manière optimale la façade contre la pluie, le vent et les variations de température.',
    'dnt.d03.p2':'Chez T.F.M. Construct BV, nous travaillons avec des produits de crépi de qualité appliqués par des artisans expérimentés. Le résultat : une finition soignée, esthétique et durable qui reste belle pendant de nombreuses années.',
    'dnt.d03.f1':'Protection optimale contre les intempéries',
    'dnt.d03.f2':'Finition soignée et esthétique',
    'dnt.d03.f3':'Nombreuses textures et couleurs disponibles',
    'dnt.d03.f4':'Respirant et hydrofuge',
    'dnt.d03.f5':'Convient pour neuf et rénovation',
    'dnt.d03.f6':'Facile d\'entretien et durable',
    'dnt.d03.f7':'Garantie 10 ans T.F.M. Construct BV',
    'dnt.d03.btn':'Devis pour crépi',
    'dnt.d04.label':'Service 04',
    'dnt.d04.h2':'Plaquettes de parement',
    'dnt.d04.p1':'Les plaquettes de parement donnent à votre façade l\'apparence de la pierre naturelle ou de la brique sans le coût élevé. Légères, résistantes à l\'humidité et esthétiquement raffinées &mdash; idéales pour la rénovation et la construction neuve.',
    'dnt.d04.p2':'Elles se posent facilement sur les façades existantes et offrent une grande variété de couleurs, textures et formats. Aussi bien pour l\'intérieur que pour l\'extérieur.',
    'dnt.d04.f1':'Aspect authentique pierre ou brique',
    'dnt.d04.f2':'Légères &amp; faciles à poser',
    'dnt.d04.f3':'Résistantes à l\'humidité &amp; faciles d\'entretien',
    'dnt.d04.f4':'Large choix de couleurs et textures',
    'dnt.d04.f5':'Convient pour intérieur et extérieur',
    'dnt.d04.f6':'Compatible avec d\'autres revêtements de façade',
    'dnt.d04.f7':'Garantie 10 ans T.F.M. Construct BV',
    'dnt.d04.btn':'Devis pour plaquettes',
    'dnt.d05.label':'Service 05',
    'dnt.d05.h2':'Badigeon à la chaux',
    'dnt.d05.p1':'Le badigeon à la chaux est une technique ancestrale à base de chaux, en plein renouveau pour les bâtiments historiques et les constructions modernes à l\'aspect authentique. T.F.M. Construct BV dispose de spécialistes expérimentés pour ce travail délicat.',
    'dnt.d05.p2':'Les propriétés respirantes de la chaux rendent le badigeon particulièrement adapté aux bâtiments patrimoniaux. Il régule le taux d\'humidité en façade et prévient les efflorescences et la condensation.',
    'dnt.d05.f1':'100% naturel et respirant (chaux)',
    'dnt.d05.f2':'Idéal pour les bâtiments historiques et patrimoniaux',
    'dnt.d05.f3':'Régule le taux d\'humidité en façade',
    'dnt.d05.f4':'Antibactérien et antifongique naturel',
    'dnt.d05.f5':'Aspect authentique et chaleureux',
    'dnt.d05.f6':'Écologique &mdash; faible empreinte écologique',
    'dnt.d05.f7':'Compatible avec les normes de restauration des monuments',
    'dnt.d05.btn':'Devis pour badigeon à la chaux',
    'dnt.cat2.label':'Catégorie 02',
    'dnt.cat2.title':'Travaux de toiture',
    'dnt.cat2.sub':'Votre toiture entre des mains expertes',
    'dnt.d06.label':'Service 06',
    'dnt.d06.h2':'Rénovation de toiture',
    'dnt.d06.p1':'Traiter une toiture vieillissante à temps vous évitera de lourdes dépenses à long terme. T.F.M. Construct BV réalise des rénovations de toiture de A à Z : de l\'inspection et du diagnostic jusqu\'au remplacement complet ou à la réparation partielle.',
    'dnt.d06.f1':'Inspection approfondie de la toiture',
    'dnt.d06.f2':'Remplacement des tuiles et ardoises',
    'dnt.d06.f3':'Réparation des gouttières et évacuations',
    'dnt.d06.f4':'Traitement des moisissures et mousses',
    'dnt.d06.f5':'Nouvelle couverture au choix',
    'dnt.d06.f6':'Garantie 10 ans sur les travaux réalisés',
    'dnt.d06.btn':'Devis pour rénovation de toiture',
    'dnt.d07.label':'Service 07',
    'dnt.d07.h2':'Isolation de toiture',
    'dnt.d07.p1':'Jusqu\'à 30% de la chaleur de votre habitation se perd par le toit. L\'isolation de toiture est donc l\'investissement le plus rentable que vous puissiez faire. T.F.M. Construct BV installe une isolation de toiture de qualité conforme à toutes les normes.',
    'dnt.d07.f1':'Isolation intérieure (entre chevrons ou plancher de grenier)',
    'dnt.d07.f2':'Isolation extérieure (sarking)',
    'dnt.d07.f3':'Valeurs d\'isolation élevées (U &le; 0,24 W/m&sup2;K)',
    'dnt.d07.f4':'Reconnu (primes possibles)',
    'dnt.d07.f5':'Problèmes de condensation résolus',
    'dnt.d07.f6':'Garantie 10 ans',
    'dnt.d07.btn':'Devis pour isolation de toiture',
    'dnt.cta.h2':'Quelle solution de façade vous convient&nbsp;?',
    'dnt.cta.p':'Notre expert vous conseille gratuitement lors d\'une visite sur place. Sans engagement, avec un avis honnête et professionnel.',
    'dnt.cta.btn':'Demander un conseil gratuit',
    /* PROJECTEN */
    'prj.hero.label':'Nos réalisations',
    'prj.hero.h1':'Réalisations',
    'prj.hero.sub':'Les résultats parlent d\'eux-mêmes',
    'prj.voor':'Avant',
    'prj.na':'Après',
    'prj.toggle':'Voir le chantier',
    'prj.situatie':'Situation',
    'prj.vraag':'Demande du client',
    'prj.aanpak':'Notre approche',
    'prj.resultaat':'Résultat',
    /* project 01 crepi */
    'prj.01.type':'Crépi',
    'prj.01.title':'Construction neuve &mdash; isolation de façade avec finition crépi',
    'prj.01.sit':'Habitation neuve sans finition de façade',
    'prj.01.vraag':'Finition complète de façade avec isolation et crépi',
    'prj.01.aanpak':'Panneaux isolants EPS posés, enduit de base avec filet d\'armature, primer et crépi comme couche de finition',
    'prj.01.res':'Façade moderne et économe en énergie avec finition crépi soignée et garantie 10 ans',
    /* project 02 steenstrips */
    'prj.02.type':'Plaquettes de parement',
    'prj.02.title':'Rénovation de façade &mdash; isolation thermique avec plaquettes de parement',
    'prj.02.sit':'Façade ancienne sans isolation',
    'prj.02.vraag':'Meilleure isolation avec un aspect authentique',
    'prj.02.aanpak':'Isolation thermique par l\'extérieur posée, finie avec des plaquettes de parement pour un aspect authentique brique',
    'prj.02.res':'Habitation économe en énergie avec un aspect brique intemporel et un confort de vie amélioré',
    /* project 03 kaleien */
    'prj.03.type':'Badigeon à la chaux',
    'prj.03.title':'Rénovation &mdash; badigeon à la chaux pour une apparence renouvelée et une protection optimale',
    'prj.03.sit':'Façade ancienne avec finition dégradée',
    'prj.03.vraag':'Apparence renouvelée et protection optimale contre l\'humidité',
    'prj.03.aanpak':'Façade nettoyée, badigeon à la chaux appliqué selon la méthode traditionnelle en plusieurs couches',
    'prj.03.res':'Aspect frais et authentique avec une excellente régulation de l\'humidité et une façade respirante',
    /* project 04 spuitkurk */
    'prj.04.type':'Enduit liège projeté',
    'prj.04.title':'Habitation résidentielle &mdash; rénovation de façade à l\'enduit liège projeté',
    'prj.04.sit':'Façade vieillissante avec enduit fissuré et décoloré',
    'prj.04.vraag':'Revêtement de façade frais et durable sans gros travaux',
    'prj.04.aanpak':'Nettoyage de la façade, réparation des fissures, enduit liège appliqué en deux couches',
    'prj.04.res':'Finition homogène et respirante &mdash; étanche et facile d\'entretien',
    /* CONTACT */
    'cnt.hero.label':'Nous contacter',
    'cnt.hero.h1':'Contact &amp; Devis',
    'cnt.form.label':'Gratuit et sans engagement',
    'cnt.form.title':'Demandez votre devis',
    'cnt.form.sub':'Remplissez le formulaire et nous vous contacterons dans les 24 heures. Ou appelez-nous directement pour un rendez-vous rapide.',
    'cnt.naam':'Nom *',
    'cnt.bedrijf':'Nom de l\'entreprise <span style="font-weight:400;text-transform:none;font-family:Inter,sans-serif;font-size:.8rem;color:#888">(facultatif)</span>',
    'cnt.tel':'Numéro de téléphone *',
    'cnt.email':'Adresse e-mail *',
    'cnt.dienst':'Service souhaité',
    'cnt.dienst.select':'Sélectionnez un service',
    'cnt.dienst.combo':'Combinaison de services',
    'cnt.dienst.advies':'Conseil / Je ne sais pas encore',
    'cnt.bericht':'Message *',
    'cnt.ph.naam':'Jean Dupont',
    'cnt.ph.bedrijf':'Votre entreprise SA',
    'cnt.ph.bericht':'Décrivez votre projet, adresse, timing souhaité...',
    'cnt.submit':'Envoyer la demande',
    'cnt.note':'Nous répondons dans les 24 heures. Vos données sont traitées de manière strictement confidentielle et ne sont jamais partagées avec des tiers.',
    'cnt.tel.label':'Téléphone',
    'cnt.tel.sub':'Lu&ndash;Ve 07:00&ndash;18:00',
    'cnt.email.label':'E-mail',
    'cnt.email.sub':'Réponse dans les 24 heures',
    'cnt.wa.label':'WhatsApp',
    'cnt.wa.sub':'Envoyez un message &mdash; réponse rapide',
    'cnt.uur.label':'Heures d\'ouverture',
    'cnt.uur.val':'Lundi &ndash; Vendredi: 07:00 &ndash; 18:00<br>Samedi: 08:00 &ndash; 14:00<br>Dimanche: Fermé',
    'cnt.werk.label':'Zone d\'intervention',
    'cnt.werk.val':'Actif dans toute la Flandre<br>Flandre-Occ., Flandre-Or., Anvers,<br>Brabant fl. &amp; Limbourg',
    'cnt.adres.label':'Adresse',
    'cnt.wa.section.label':'Le moyen le plus rapide',
    'cnt.wa.h2':'Vous préférez chatter via WhatsApp&nbsp;?',
    'cnt.wa.p':'Envoyez-nous un message et nous répondons le plus vite possible. Vous pouvez aussi envoyer des photos de votre façade via WhatsApp&nbsp;!',
    'cnt.wa.btn':'Chat via WhatsApp',
    /* OVER ONS */
    'ons.hero.label':'T.F.M. Construct BV',
    'ons.hero.h1':'À propos de T.F.M. Construct BV',
    'ons.story.label':'Notre histoire',
    'ons.story.title':'Fondée sur la passion du savoir-faire',
    'ons.story.p1':'T.F.M. Construct BV est née d\'une profonde passion pour les travaux de construction et de la conviction inébranlable que chaque bâtiment mérite une finition qualitative et durable &mdash; aussi bien la façade que la toiture. Dès le début, nous avons résolument choisi le savoir-faire, les matériaux de qualité et une approche personnelle.',
    'ons.story.p2':'Actifs dans toute la Flandre, de la côte aux Campines, nous construisons chaque jour la réputation qui nous distingue : conseils honnêtes, prix transparents et un résultat dont nous sommes aussi fiers que nos clients.',
    'ons.story.p3':'Nos équipes sont composées d\'artisans expérimentés qui abordent chaque projet avec le même soin et la même dévotion, quelle que soit l\'envergure. Qu\'il s\'agisse d\'une finition crépi, d\'une rénovation de façade à l\'enduit liège, d\'une rénovation de toiture ou d\'une isolation de toiture &mdash; T.F.M. Construct BV livre toujours le meilleur résultat.',
    'ons.story.p4':'Nous croyons aux relations à long terme avec nos clients. C\'est pourquoi nous offrons une garantie de 10 ans sur tous nos travaux de façade et de toiture et restons disponibles après la livraison.',
    'ons.val.label':'Nos valeurs fondamentales',
    'ons.val.title':'Ce en quoi nous croyons',
    'ons.kwaliteit.h':'Qualité',
    'ons.kwaliteit.p':'Nous travaillons exclusivement avec des matériaux certifiés de marques reconnues. Chaque projet est réalisé avec le souci du détail et conformément aux normes les plus strictes.',
    'ons.betrouw.h':'Fiabilité',
    'ons.betrouw.p':'Nous tenons nos engagements. Communication transparente, devis clairs sans frais cachés et exécution dans les délais sont nos principes de base.',
    'ons.vakman.h':'Savoir-faire',
    'ons.vakman.p':'Nos artisans bénéficient de nombreuses années d\'expérience et suivent des formations continues. Les travaux de façade et de toiture sont des métiers que nous exercons avec fierté.',
    'ons.why.label':'Pourquoi nous choisir',
    'ons.why.title':'Vos avantages avec T.F.M. Construct BV',
    'ons.why.sub':'Nous nous distinguons par notre approche personnelle, notre expertise technique et notre garantie de qualité inébranlable. Voici les principales raisons pour lesquelles nos clients nous choisissent :',
    'ons.adv1':'Garantie 10 ans sur tous les travaux de façade et toiture',
    'ons.adv2':'Visite gratuite et devis sans engagement',
    'ons.adv3':'Devis dans les 48 heures après la visite',
    'ons.adv4':'Actif dans toute la Flandre',
    'ons.adv5':'Entrepreneur reconnu &mdash; artisan certifié',
    'ons.adv6':'Uniquement des matériaux de haute qualité et certifiés',
    'ons.adv7':'Tarification transparente et honnête',
    'ons.adv8':'Interlocuteur personnel pendant le chantier',
    'ons.adv9':'Chantier propre et sécurisé garanti',
    'ons.adv10':'Intervention rapide en cas de questions ou problèmes',
    'ons.adv11':'Équipes expérimentées spécialisées par service',
    'ons.adv12':'Suivi et service après livraison',
    'ons.cta.h2':'Prêt à rénover votre façade ou votre toiture&nbsp;?',
    'ons.cta.p':'Contactez-nous dès aujourd\'hui. Nous planifions une visite gratuite et vous remettons un devis transparent sans engagement.',
    'ons.cta.btn':'Nous contacter',
    /* BREADCRUMB */
    'bc.home':'Accueil',
    'bc.diensten':'Services',
    'bc.projecten':'Réalisations',
    'bc.contact':'Contact',
    'bc.over':'À propos',
  }
};

function applyLang(lang) {
  const T = LANG[lang];
  if (!T) return;
  document.documentElement.lang = lang === 'fr' ? 'fr-BE' : 'nl-BE';
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const v = T[el.dataset.i18n];
    if (v !== undefined) el.innerHTML = v;
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const v = T[el.dataset.i18nPh];
    if (v !== undefined) el.placeholder = v;
  });
  document.querySelectorAll('[data-i18n-opt]').forEach(el => {
    const v = T[el.dataset.i18nOpt];
    if (v !== undefined) el.textContent = v;
  });
  document.querySelectorAll('[data-i18n-aria]').forEach(el => {
    const v = T[el.dataset.i18nAria];
    if (v !== undefined) el.setAttribute('aria-label', v);
  });
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
    btn.setAttribute('aria-pressed', btn.dataset.lang === lang);
  });
  localStorage.setItem('tfm_lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('tfm_lang') || 'nl';
  applyLang(saved);
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => applyLang(btn.dataset.lang));
  });
});
